# Generated by Django 4.0 on 2021-12-31 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('subtitle', models.CharField(blank=True, default='WEBSITE', max_length=35)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
                ('imageurl', models.URLField()),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('icon1', models.CharField(max_length=25)),
                ('icon2', models.CharField(max_length=25)),
                ('icon3', models.CharField(max_length=25)),
            ],
        ),
    ]
